### PR TITLE
please create an envirement for mt5 

### PR DESCRIPTION
**Pull request by salah2025**
please create an envirement for mt5

### CODE REVIEW

**Comment by zhumingpassional** [comment]
what do you mean by mt5?

**Comment by XiaoYangLiu-FinRL** [comment]
> please create an envirement for mt5

Please explain in details… I do not follow here. Thanks!

**Comment by marcipops** [comment]
> > please create an envirement for mt5
> 
> Please explain in details… I do not follow here. Thanks!

@salah2025 do you mean Metatrader 5?  (www.metatrader5.com)

**Comment by marcipops** [comment]
There is a limited python library for MT5: https://www.mql5.com/en/docs/integration/python_metatrader5 but as you can see it is missing vital trading operations.

However, I have not gone down this path and integrate FinRL with Metatrader, but have integrated FinRL with the broker API to get data and issue trading operations (see https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/3-Practical/FinRL_PaperTrading_Demo.ipynb for an example integration with Alpaca broker).  You can then still use MT5 for the charting.  The other reason is that MT5 is a desktop application, not designed to be deployed on VPC, so it will be vulnerable to power or Internet access loss.

I didn't want to change the paper trading demo and introduce another version (as most of the trading logic would be the same). WIth the same approach as the layered data processors, I am creating a specific broker layer that sits beneath the papertrading demo (with small mods to point to this layer).   Hopefully then we will have a generic papertrading demo, that supports specific broker implementations for trading operations.

Hope that helps.

**Comment by TSwetnam** [comment]
If people are still interested in this is relatively easy to do.

You just need to import and initialise the MT5 package and then make a copy of the data processor file and put something like the below in place of the loop to download data for whichever data processor you're using.

This example is hard coded to the hourly timeframe.

for tic in ticker_list:
    temp_df = pd.DataFrame(mt5.copy_rates_range(tic, mt5.TIMEFRAME_H1, start_date, end_date))
    temp_df["tic"] = tic
    data_df = pd.concat([data_df, temp_df])

**Pull request merged**
