### PR TITLE
switch to pytest + running flake8 & black

### PR DESCRIPTION
**Pull request by DominiqueGarmier**
- switched all tests form unittest to pytest as per requirements.txt
  - renamed tests folder to `/tests` as per python convention
  - marked unimplemented tests with `mark.xfail` marked one test which was previously failing as `mark.skip`
  - ignored google api deprecation warnings see: https://github.com/googleapis/python-api-common-protos/issues/23
  ##### TODO (for another PR)
  - implement all test
  - improve test couverage
  - stop using deprecated methods such as [`df.append`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.append.html)

- updated .pre-commit-config.yaml with some nice to have hooks
- ran flake8 + black and formatted the whole codebase to be mostly pep8 compliant

### CODE REVIEW

**Comment by zhumingpassional** [comment]
Thanks for your valuable codes and suggestions. We will refactor FinRL in the next days.

**Comment by zhumingpassional** [comment]
There are several conflicts that should be resolved, since a previous PR has been merged. Could you please pull it again, and  revise it based on the newest version?

**Comment by zhumingpassional** [comment]
Conflicting files
finrl/config_private.py
finrl/finrl_meta/data_processors/processor_yahoofinance.py
finrl/finrl_meta/env_stock_trading/env_stock_papertrading.py
finrl/main.py
finrl/trade.py

**Comment by DominiqueGarmier** [comment]
> Conflicting files
> finrl/config_private.py
> finrl/finrl_meta/data_processors/processor_yahoofinance.py
> finrl/finrl_meta/env_stock_trading/env_stock_papertrading.py
> finrl/main.py
> finrl/trade.py

it seems im too dumb to fix this give me a second

**Comment by DominiqueGarmier** [comment]
nice, finally figured out that i had to merge upstream and only run linters after

**Comment by zhumingpassional** [comment]
1 Why did you revise README.md, and it seems that you added/removed several spaces. Similiar revisions also exist in some other files, e.g., docs/Makefile, docs/.readthdocs.yaml.
2 You replaced " " using ' ', it there any reasons/advantages? 
3 Why did you revise the tutorials? 
4 With respect to import, I think the following is better, and do you have any idea about it? 
from finrl.config import (
    DATA_SAVE_DIR,
    TRAINED_MODEL_DIR,
    TENSORBOARD_LOG_DIR,
    RESULTS_DIR,
    INDICATORS,
    TRAIN_START_DATE,
    TRAIN_END_DATE,
    TEST_START_DATE,
    TEST_END_DATE,
    TRADE_START_DATE,
    TRADE_END_DATE,
    ERL_PARAMS,
    RLlib_PARAMS,
    SAC_PARAMS,
    ALPACA_API_BASE_URL,
)

**Pull request closed without merging**
