### PR TITLE
Bug fix to negative stock holding

### PR DESCRIPTION
**Pull request by kelvinlyy**
@BruceYanghy @spencerR1992 @XiaoYangLiu-FinRL

### CODE REVIEW

**Comment by kelvinlyy** [comment]
This is to solve the bug I found in: https://github.com/AI4Finance-Foundation/FinRL/issues/630

**Comment by zhumingpassional** [comment]
Only the calculation of available_amount should be revised. Why did you revise other codes?

**Comment by kelvinlyy** [comment]
Hi, I just changed the line of calculating the available_amount. I also noticed that the git history showed I changed the whole file, but it was what it was when I committed my change.

**Comment by zhumingpassional** [comment]
Could you please pull the code from master again, and revise, and push it again?

**Comment by XiaoYangLiu-FinRL** [comment]
Your codes may be an older version....how about revising the latest codes, and then submitting them?  Thanks very much.

**Pull request closed without merging**
