### PR TITLE
Add example of using Taiwan exchange market data, fix bug and more compatibility.In tickerlist, add Taiwan top 50 company list.

### PR DESCRIPTION
**Pull request by Charliesj0129**

### CODE REVIEW

**Comment by zhumingpassional** [comment]
why did you revise config_tickers.py and config?
This branch has conflicts that must be resolved. pls check it.
have you tested it?

**Comment by Charliesj0129** [comment]
sorry about that 😔, I don't test it. At first I think modify it is a good idea. But after I just put tickerlist in my example. I don't notice that I have modified it.

**Comment by Charliesj0129** [comment]
sorry about that 😔, I don't test it. At first I think modify it is a good idea. But after I just put tickerlist in my example. I don't notice that I have modified it.

**Comment by zhumingpassional** [comment]
pls revise it and resubmit it

**Pull request closed without merging**
