### PR TITLE
Download data with one query

### PR DESCRIPTION
**Pull request by dev590t**
Related to https://github.com/AI4Finance-Foundation/FinRL/issues/685.

### CODE REVIEW

**Comment by zhumingpassional** [comment]
Thanks for your effort. 
have you tested it?

**Comment by dev590t** [comment]
yes, the new version return the same value than the old version, except the old version contain a column index with NaN in entire column. This column is useless. The new version 's df hasn't this columns, so:
```
data = # returned value of old download_data
data2 = # returned value of new download_data
data.drop('index',axis=1) == data2
```

**Comment by dev590t** [comment]
Just wait a moment before merge the PR. I have tested the code for intraday data, but for day data that seem have a problem. I'm working on that

**Comment by dev590t** [comment]
@zhumingpassional The initial version of download_data can't run if time_interval = '1D'. I have fixed the bug. You can continue the review now.

**Comment by zhumingpassional** [comment]
Thanks for your valuable codes. we will review and test it.

**Pull request merged**
