### PR TITLE
Add CPU-only support to Docker builds

### PR DESCRIPTION
**Pull request by merlos**
Allows to build the docker container in CPU-only systems as specified #132 

Includes the following changes
- Created `Dockerfile-cpu` which is the original one it only changes the first line to be `FROM stablebaselines/rl-baselines3-zoo-cpu:0.11.0a4`
- In `build_container.sh` script added the option `--cpu` option which uses the `Dockerfile-cpu` as well as some usage documentation.
- In README
   - Added documentation on how to build on CPU-only systems
   - Applied [prettier](https://prettier.io/) to markdown 
   - Removed $ from some bash fenced blocks
   - Fixed a couple of typos

@spencerR1992

### CODE REVIEW

**Comment by XiaoYangLiu-FinRL** [comment]
@spencerR1992  is this updated PR meets the expectation from #132 ?

**Comment by merlos** [comment]
@spencerR1992  @XiaoYangLiu-FinRL any update on this?

**Review by spencerR1992 — APPROVED** [review]
Looks good, thanks for this contribution!

**Comment by spencerR1992** [comment]
@merlos can you please resolve the conflicts and then this can be merged?

**Comment by merlos** [comment]
@spencerR1992 Thanks!

**Pull request closed without merging**
