### PR TITLE
fix: Moved device parameter from DRLAgent initialization to get_model method

### PR DESCRIPTION
**Pull request by StevenChen16**
fix: Moved device parameter from DRLAgent initialization to get_model method

- Removed the incorrect use of `device` in the `DRLAgent` constructor, as `device` is not a valid parameter for initialization.
- Added `device` parameter correctly to the `get_model` method, allowing models to be trained on GPU (using `cuda`) or CPU as specified during model creation.
- Ensured the model uses the appropriate device when calling `get_model`.

### CODE REVIEW

**Comment by zhumingpassional** [comment]
thanks for your codes.

in finrl/agents/stablebaselines3/models.py, why do you fix the device as cpu? If users use gpu, hot to set it? I suggest to use GPU_ID, if it is -1, use cpu, if it > 0, use gpu. how do you think about it?

**Comment by StevenChen16** [comment]
> thanks for your codes.
> 
> in finrl/agents/stablebaselines3/models.py, why do you fix the device as cpu? If users use gpu, hot to set it? I suggest to use GPU_ID, device = torch.device(f'cuda:{GPU_ID}' if torch.cuda.is_available() and GPU_ID >= 0 else 'cpu') if it is -1, use cpu, if it > 0, use gpu. how do you think about it?

from my perspective, In the original code there was no option to use the GPU, so I defaulted the program to use the CPU. after I added the ability to use the GPU the user could select it.

**Comment by zhumingpassional** [comment]
have you tested it? does work well now?

**Comment by StevenChen16** [comment]
I think so🤔

**Comment by zhumingpassional** [comment]
I reverted this PR.

there are several revisions in this PR. I suggest to split the PR to several ones since we hope that a PR only represents a revision/function. 
could you pls submit them one by one. And I will test them one by one.

**Pull request merged**
