### PR TITLE
Update funciton that use deprecated v1 alpaca method to download bars

### PR DESCRIPTION
**Pull request by ObaidaAlhaasan**
Code credit goes to @yizhangliu, thank you so much for your code!

The reason I'm creating this PR on behalf of sir yizhangliu is to save some time cuz I need the fix to continue on my sample

### CODE REVIEW

**Comment by yizhangliu** [comment]
@ObaidaAlhaasan 
You are welcome.

**Comment by XiaoYangLiu-FinRL** [comment]
Thx.

**Comment by ObaidaAlhaasan** [comment]
Hi @zhumingpassional , could you please review this PR and let me know if it needs any edit

Thank you in advance!

**Comment by zhumingpassional** [comment]
@ObaidaAlhaasan  

OK.  I will review it today.

**Comment by ObaidaAlhaasan** [comment]
Thank you sir!

**Comment by zhumingpassional** [comment]
Not at all. 

Merged.

**Pull request merged**
