### PR TITLE
Shenlei151 flexibility enhance

### PR DESCRIPTION
**Pull request by shenlei515**
Fixes AI4Finance-Foundation/FinRL#481
I adjust a few lines of code in FinRL to make it more flexible for problems that I met with in my own project, though these changes may be aiming for my project, I think it might be useful to extend the feature of FinRL including:
feature extension:
  1. support different costs_pct with different stocks(fix it by modifying **finrl/finrl_meta/env_stock_trading/env_stocktrading.py function __init__**)
  2. able to hold stocks when initial instead of only cash(fix it by modifying **finrl/finrl_meta/env_stock_trading/env_stocktrading.py function __init__**)
  3. support to define time that trading is forbidden(fix it by modifying **finrl/finrl_meta/env_stock_trading/env_stocktrading.py function _buy_stock and function _sell_stock**)
  4. able to get state of everyday when trading(fix it by adding **finrl/finrl_meta/env_stock_trading/env_stocktrading.py function save_state_memory and finrl/drl_agents/stablebaselines3/models.py function DRL_prediction**)
bug:
 5.fix bug that when buying stocks it didn't consider conmmision, which will cause the cash < 0 (fix it by modifying **finrl/finrl_meta/env_stock_trading/env_stocktrading.py function _buy_stock**)  
These features are needed in my project, I hope it will help enhance the flexibility of FinRL
Also, I put part of my project code to explan why and how to use the features that I add in **RL_stock.py**, I hope it will help you understand the changes I made.

### CODE REVIEW

**Comment by zhumingpassional** [comment]
Thanks for your codes. 

It's great. I suggest to add type hint in all functions. In the new version, type hint will be added.

**Comment by XiaoYangLiu-FinRL** [comment]
@shenlei515  some research team contacted me about errors, they have a submission ddl, so I reverted this PR.

**Comment by shenlei515** [comment]
> @shenlei515 some research team contacted me about errors, they have a submission ddl, so I reverted this PR.

Yes, I see some errors caused by my changes, I think my change only apply to my situation, maybe it need some modifications to be adapted for other situations. I am sorry for the result caused by my unreasonable PR.

**Comment by XiaoYangLiu-FinRL** [comment]
It is OK, not a big issue. 
We may need to make the codes more standard so that everybody can contribute more easily.

**Comment by zhumingpassional** [comment]
@shenlei515 
Could you please describe the function of RL_stock.py? How to use it? 
Thanks you very much. 

In addition, I think RL_stock.py is not suitable to be in the current folder.

**Comment by zhumingpassional** [comment]
What's the length of initial_list? What does initial_list mean?

**Comment by shenlei515** [comment]
@zhumingpassional 
RL_stock is a example to explain how to use the changed RLlib and why I need to modify the RLlib

First element of initial_list is the cash we have in the beginning, rests of it are the share of stocks we have at first. So the length of initial_list is supposed to be 1+stock_dimension.

**Comment by zhumingpassional** [comment]
Thanks for your reply. 

I suggest initial_list is seperated to two parts (parameters), initial_amount and num_stock_shares, since they have different units (money, and num of shares).

**Comment by shenlei515** [comment]
> @shenlei515
> 
> Thanks for your reply.
> 
> I suggest initial_list is seperated to two parts (parameters), initial_amount and num_stock_shares, since they have different units (money, and num of shares).

Yes, that make more sense.

**Comment by zhumingpassional** [comment]
@shenlei515  Could you please push a PR to revise it if you have enough time? Only for this point (initial_list is seperated to two parts).

**Comment by shenlei515** [comment]
> 

I have pulled a request to revise it.

**Comment by zhumingpassional** [comment]
Merged. Thanks for your valuable codes.

**Pull request merged**
