### PR TITLE
Add DRLlibv2.py

### PR DESCRIPTION
**Pull request by Athe-kunal**
This is an alternative to the current RLlib agent with hyperparameter optimization pipeline using Ray tune

### CODE REVIEW

**Review by Athe-kunal — COMMENTED** [review]
Just one line update

**Comment by zhumingpassional** [comment]
good codes. 
thanks for your effort.

**Comment by zhumingpassional** [comment]
I have several suggestions: 
float | int can be revised as Union[float, int]
str | list[str] can be revised as Union[str, List[str]]
None | int can be revised as optional[int]

could you pls improve the codes?

**Review by Athe-kunal — COMMENTED** [review]
Changed as per suggestion

**Comment by Athe-kunal** [comment]
Thank you for your suggestions @zhumingpassional 
I have done the necessary changes

**Comment by zhumingpassional** [comment]
however, some are not changed, e.g., float | int.
 pls double check it.

**Review by Athe-kunal — COMMENTED** [review]
This meets all the required format in the template

**Comment by zhumingpassional** [comment]
looks much better now.

with respect to num_gpus: Union[float, int], the type is int, and Union[None, int] can be revised as Optional[int]. 
with respect to function, we'd better point out the return type, e.g., train_tune_model.

could you pls revise it again? thanks for your effort.

**Comment by Athe-kunal** [comment]
For num_gpus, the value can be fractional, like for each trial allocate this percentage of GPU. It is a Ray feature to allocate GPU to multiple trials and number of gpus. And for checkpoint_num_to_keep, None means that keep all the checkpoints. So both None value and int can be passed

**Comment by zhumingpassional** [comment]
ok. 
it's good

**Pull request merged**
