### PR TITLE
Bug Fix on Yahoo Finance Data Downloader

### PR DESCRIPTION
**Pull request by tylerliu**
The current version of downloader has a bug that only downloads data from the first ticker, and skips the rest.  This patch should fix the bug.

### CODE REVIEW

**Comment by zhumingpassional** [comment]
are you sure？
I ran several notebooks and it works.

could you pls paste the param settings, how to call the yahoo api, and the results?

**Comment by dytsou** [comment]
@zhumingpassional 
I also faced the same problem. The api would only download the first ticker in the list since the date didn't reset to the start date.

The way I called the YahooFinanceProcessor is like this:

```python
processor = YahooFinanceProcessor()
data = processor.download_data(
    ticker_list=["AAPL", "AMGN" , "AXP", "BA"],
    start_date="2024-01-01",
    end_date="2024-01-05",
    time_interval="1D",
)
``` 
and the result would only have the first stock in ticker_list (AAPL) as 
image

**Comment by zhumingpassional** [comment]
@tylerliu 
Sorry. 
The branch has conflicts. pls resubmit the PR  after pulling the newest repo

**Comment by dytsou** [comment]
@zhumingpassional I've just created a PR solving the conflict in PR #1242

**Pull request closed without merging**
