### PR TITLE
Resolved #726

### LINKED ISSUE #726: TypeError in Stock_Fundamental.ipynb
run in google colab:
https://colab.research.google.com/github/AI4Finance-Foundation/FinRL/blob/master/tutorials/1-Introduction/Stock_Fundamental.ipynb

code:
df_account_value_ppo, df_actions_ppo = DRLAgent.DRL_prediction(
    model=trained_ppo, 
    environment = e_trade_gym) if if_using_ppo else None

df_account_value_ddpg, df_actions_ddpg = DRLAgent.DRL_prediction(
    model=trained_ddpg, 
    environment = e_trade_gym) if if_using_ddpg else None

df_account_value_a2c, df_actions_a2c = DRLAgent.DRL_prediction(
    model=trained_a2c, 
    environment = e_trade_gym) if if_using_a2c else None

df_account_value_td3, df_actions_td3 = DRLAgent.DRL_prediction(
    model=trained_td3, 
    environment = e_trade_gym) if if_using_td3 else None

df_account_value_sac, df_actions_sac = DRLAgent.DRL_prediction(
    model=trained_sac, 
    environment = e_trade_gym) if if_using_sac else None

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-45-32d3a01eb334> in <module>
      1 df_account_value_ppo, df_actions_ppo = DRLAgent.DRL_prediction(
      2     model=trained_ppo,
----> 3     environment = e_trade_gym) if if_using_ppo else None
      4 
      5 df_account_value_ddpg, df_actions_ddpg = DRLAgent.DRL_prediction(

TypeError: cannot unpack non-iterable NoneType object

### PR DESCRIPTION
**Pull request by craquinterogo**
Resolved #726 

Additional modifications
- Test test/test_core.py
- docStrings of script Stock_NeurIPS2018_SB3.py

### CODE REVIEW

**Comment by craquinterogo** [comment]
Again I apologize, I had a problem with my branch, so I'm restarting the pull request. Regards.

**Comment by zhumingpassional** [comment]
thanks for your work. we will test it.

**Comment by zhumingpassional** [comment]
@craquinterogo 
I can not see the changes of tutorials/1-Introduction/Stock_Fundamental.ipynb.
could you pls describe which changes you do?

**Comment by craquinterogo** [comment]
@zhumingpassional The change of tutorials/1-Introduction/Stock_Fundamental.ipynb is basically this (please see image attached).

Instead using None as return on each else condition, is returned an array [None, None], because is the case when try to unpackage two values.

image

**Comment by zhumingpassional** [comment]
@craquinterogo thanks for your reply. this PR is merged.

**Pull request merged**
