### PR TITLE
Try to make run FinRL_PaperTrading_Demo.ipynb

### PR DESCRIPTION
**Pull request by dev590t**
FinRL_PaperTrading_Demo.ipynb raise many exception, maybe because some code is outdated.
I have attempt to make run FinRL_PaperTrading_Demo.ipynb until part 4.
The PR contains 
- a temporary solution to bypass the issue #604 in commit [333285a](https://github.com/AI4Finance-Foundation/FinRL/pull/619/commits/333285a006edf9defd090540d674f20cdbdc5632).
- @DEVNODEREACT
[Update code to compatible with last version alpaca](https://github.com/AI4Finance-Foundation/FinRL/pull/619/commits/eb190d20b290ab592d441de6f946ea1f8e148597)

### CODE REVIEW

**Comment by zhumingpassional** [comment]
I saw you use data_df['timestamp'] to replace data_df['time']. Does the previous code data_df['time'] raise errors?

Is turb_df = self.api.get_bars(["VIXY"], time_interval, limit=1).df["VIXY"] equal to turb_df = self.api.get_bars(["VIXY"], time_interval, limit=1).df ???

**Comment by dev590t** [comment]
alpacahq/alpaca-trade-api-python has recently updated its API. I can't run the notebook with alpaca_trade_api==2.1.0.
For more information, you can look my commit message in https://github.com/AI4Finance-Foundation/FinRL/pull/619/commits/eb190d20b290ab592d441de6f946ea1f8e148597

**Comment by zhumingpassional** [comment]
Thanks for your valuable reply. Good codes.

I will merge this PR.

The alpaca processor also exists in finrl meta https://github.com/AI4Finance-Foundation/FinRL-Meta. Could you please submit a PR in finrl meta? Thank you very much.

**Comment by dev590t** [comment]
I will take a look when I have time

**Pull request merged**
