### PR TITLE
Fix-threading-join()

### PR DESCRIPTION
**Pull request by marcipops**
- Removed the threading from a couple of calls (await market open and trade).
- Added parallel threading start, followed by joining.

### CODE REVIEW

**Comment by zhumingpassional** [comment]
have you tested it?
how about the performance of parallel threading?
does it need to add the num of cores?

**Comment by zhumingpassional** [comment]
@marcipops 
This branch has conflicts that must be resolved
Conflicting files
tutorials/FinRL_PaperTrading_Demo.ipynb

pls revise it

**Comment by marcipops** [comment]
Please explain 'num of cores'. 

Currently this PR is simpy to offer a fix for the issue of lack of parallelism of trades. The code now multi-threads properly - the joins are invoked after all the threads have started.

**Comment by zhumingpassional** [comment]
for example, there are 8 cpu cores, and 10 threads are opened.

**Comment by marcipops** [comment]
I'm not an expert at this, so I'll leave to someone more qualified, but it looks like "Unfortunately, in many cases your code can only run one thread at a time, due to Python’s global interpreter lock, the GIL for short": source:  https://pythonspeed.com/articles/python-gil/

**Pull request closed without merging**
