### PR TITLE
processor_alpaca.clean_data fix for tickers data alignment.

### PR DESCRIPTION
**Pull request by kruzel**
1. processor_alpaca.py: clean_data fix for tickers data alignment.
2. preprocessors.py: add date_column to all methods
3. other minor compatibility fixes

issue: https://github.com/AI4Finance-Foundation/FinRL/issues/835

### CODE REVIEW

**Comment by zhumingpassional** [comment]
thanks for your effort

have you tested it?

in several functions (e.g., clean_data, add_turbulence, add_vix), you added a param date_column, which will cause many changes for other tutorials. and can you use other other methods to solve this problem without adding params?

**Comment by kruzel** [comment]
hi ming,
the date_column have default value as before so it should not affect any
existing code.

Ofer Kruzel
M: +972 (54) 4516627

**Comment by zhumingpassional** [comment]
To unify the param list of functions of all data processors,  it does not need to use the param date_column, and we can directly use "data" or "timestamp".  

do you have any ideas about it?

**Comment by kruzel** [comment]
if it's a problem then drop the changes of this file, its not related to
the bug fix.
Ofer Kruzel
M: +972 (54) 4516627

**Comment by kruzel** [comment]
ok, I'll prepare it
Ofer Kruzel
M: +972 (54) 4516627

**Pull request closed without merging**
