### PR TITLE
added __main__.py file removed some dead code and formatted main.py

### PR DESCRIPTION
**Pull request by DominiqueGarmier**

### CODE REVIEW

**Comment by DominiqueGarmier** [comment]
> Why did you use kwargs = ( {} ) to replace kwargs = {}?

your pre-commit hook, black did that. I think its because the comment at the end was too long

**Comment by zhumingpassional** [comment]
In main.py, why did you remove main()
and add   raise SystemExit(main())?

**Comment by DominiqueGarmier** [comment]
> In main.py, why did you remove main() and add raise SystemExit(main())?

when running `main.py` within other cli scripts it will return the propper exit code i.e 0 for successful anything else for not successful. As you may have noticed i also changed `main()` to return `0` instead of `None`. See https://en.wikipedia.org/wiki/Exit_status

**Comment by zhumingpassional** [comment]
Impressive codes.

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks very much for your patience @DominiqueGarmier !  Appreciate your help.

**Comment by DominiqueGarmier** [comment]
fyi you should probably "squash merge" PRs with multiple commits, it will basically squash all the commit into one. 
image
(picture from one of my repos)

**Pull request merged**
